### ISSUE TITLE
createMuiTheme deprecated in ^4.12.1

### ISSUE THREAD

**Issue by bertearazvan** [DHI/react-components#161]
If using the latest materialUI version when the Theme is used in other projects, it fails because the createMuiTheme seems to be deprecated. 

This should be fixed and the ThemeProvider should be updated so we can use it with the latest MuI version.

However, it works with the version `4.11.2`

![df229c53e3120140a115ed0b8b590538](https://user-images.githubusercontent.com/30385700/124894633-1ef36980-dfdc-11eb-8111-681788ad0950.png)

@rosudhi Maybe you have a better overview of that component?

**Comment by rosudhi** [comment]
just had a quick look on the latest version and this changes happening since 4.12.x version. and yes, i think it needs to be updated also, needs takes some time to see the changes.

![image](https://user-images.githubusercontent.com/46663012/124898405-5af0f380-e009-11eb-961c-c9dd677c9d5d.png)

![image](https://user-images.githubusercontent.com/46663012/124898466-6b08d300-e009-11eb-8538-d410c27a65a4.png)

**Comment by bertearazvan** [comment]
Could probably be simply replaced by this:

![3c2ab2a459a3b32a16bb3912e62bef7d](https://user-images.githubusercontent.com/30385700/124930261-7821c400-e001-11eb-96cc-77e8ce04e1e4.png)
