### ISSUE TITLE
CONTRIBUTING guidelines document

### ISSUE THREAD

**Issue by nfour** [DHI/react-components#73]
For discussion of policies/concepts to fill our CONTRIBUTING.md

**Comment by nfour** [comment]
One concept I'd like to highlight is on how we compose our components.

In order to support re-usability it will help to avoid tight coupling. 

For example, instead of an AccountsManager component (List accounts, edit accounts, see permissions, delete accounts etc.) being coupled to Domain Services behavior, we present two components in its place:

- DomainServicesAccountsManager
- AccountsManager

Where "AccountsManager" is dumb and all dependencies are provided as props or React Context - it can then be made to work with any data, a pure view.

And "DomainServicesAccountsManager" wraps "AccountsManager" with Domain Services behaviors - meaning it can be a lot easier to "plug n play" & configure.

- Someone determines that X component would be great if it could work with Y data
- Make an issue discussing the task & send a link to relevant contributors
- If agreeable, create a PR and link it to the issue, then close both issue & PR on merge

If you're writing a component dealing with the specific details of an API, there is likely no point to genericize the view layer, so it's something to keep in mind on a per-case basis.

Would be ideal if creators of new components had this in mind so we can get this win earlier in the process.

**Comment by JeanLoureiro** [comment]
> Where "AccountsManager" is dumb and all dependencies are provided as props or React Context - it can then be made to work with any data, a pure view.

Props would be good on small components. However, we have components witth more than 20 props and we should keep it consistent accross every component we develop here. So, React Context would be the way to go IMO. Does anyone else have any suggestion?

To add to your comment above @nfour. 

The components should follow the same structure as JobList.
![image](https://user-images.githubusercontent.com/2092318/107452344-be7b1000-6b94-11eb-9461-b467d90e5b6f.png)
-- ComponentFolder
---- ComponentName.stories.tsx
---- ComponentNameFolder
------ ComponentName.tsx
------ style.ts (if we continue with Material-UI)
------ type.ts
------ helpers (Folder) 

***helpersFolder** is in place to keep the main file as clean as possible ( I have a rule of thumb, if my component reaches 300 lines, it is a sign it should be refactored... I know sometimes it is hard :) ). 
Very important, check the **/utils** folder before create a helper function to avoid duplication. And feel free to update any utils function if necessary.




any other suggestion? I might come back to this comment and add more as things come to mind.

**Comment by rihr** [comment]
I would like to go over a few things that should be considered regarding the general setup of the repository, which I think would bring much more clarity and allow for us in GRAS to begin contributing already.
This isn't necessarily something that should be put in the CONTRIBUTING.md file - more specific guidelines could be derived if the ideas here are agreeable.

As previously mentioned, our priority in GRAS would be to add in the smaller, atomic components, from which larger ones can be composed. Without a shared library, we have to keep copying these various smaller components over to most of our projects.

These are the sort of components that could be useful immediately, not only in our projects, but also as ones to use for then making the larger components in this repository.
They should also be the easiest and quickest to add, and they can be added on a as-needed basis.

Larger, more complex and composed components could somehow be separated from the more atomic ones.
It could be a separate library, as a package within a monorepo, or as a separate part of the same library.
I think it makes sense to make this distinction because different guidelines could be established for each of these two types of components, and it could keep the repository much cleaner, while providing the flexibility of being able to use the atomic components to both make the larger components in the library, while also being able to use them independently in our projects.

### Atomic and simple UI components
#### Structure
Since we're probably going to keep using Material-UI, I think it would make sense to take a lot of inspiration from the naming, file structure and other conventions that can be seen in the Material-UI/core source.
Most importantly, each component should be in its own directory, which contains the component file and optionally its theme, type, test files. They should not have any child components.

### Larger components
An example of a larger component would be any of the ones so far proposed in the "wishlist". Each of them could be broken down into atomic components, which should be put in the previously mentioned component package, even if they immediately may not have any other use.

#### Structure
I agree with the suggestions above, regarding the way these components could be structured, though I think depending on how complex the component in question is, we should allow for some flexibility.

### Linting
To keep the whole syntax as consistent as possible and take the work off of reviews and nitpicking,
I would suggest adding more rules to the existing ones in this repository, especially ones relating
to TypeScript.

Something to potentially look at could be this, or similar config libraries
https://github.com/iamturns/eslint-config-airbnb-typescript
### Contributing
Would just like to mention that I believe the main role of the active maintainers/representatives from each team is to actively maintain the library and add in new components quickly so that they can be used when needed in the teams they represent.

They should avoid situations where developing your own component in a team is significantly easier than sharing it, whatever the reason may be at a given time.

### Publishing, compiling, versioning
The existing setup looks sufficient, though it would be nice to eventually have a CI pipeline automate testing, linting, versioning and publishing of the libraries - I think we would benefit from very fast and frequent automated releases.

#### Note on changing components
When contributing and modifying existing components that are already being implemented in projects, it might make sense to avoid adding breaking changes to the existing props and styling of a component.
It may also be worth at some point decide on a way to deprecate components and then make a new version when large breaking changes have to be added.

### Other considerations
Should every component be added to storybook?
To what extent, if at all, should testing be added?

**Comment by elbys** [comment]
Hey,

@JeanLoureiro  How do you see the simple components being organized in this repo ?

**Comment by JeanLoureiro** [comment]
Hey @elbys,

if I understood you question well. We can use Material UI library as Simple Components (Buttons, Typography, Cards, Grid and so on) and put them together on the fly when we need them rather than building a component grouping them. 

Does it make sense? 

cc: @FranzThomsen1089 as I know you have the big picture 😃 


> The existing setup looks sufficient, though it would be nice to eventually have a CI pipeline automate testing, linting, versioning and publishing of the libraries - I think we would benefit from very fast and frequent automated releases.

I like that.


> I agree with the suggestions above, regarding the way these components could be structured, though I think depending on how complex the component in question is, we should allow for some flexibility.

Sure. This is how we are doing in Australia, doesn't mean it is the right way 👍 how would you suggest?

> Linting

Somehow I struggled setting it up on my machine (working on Windows after 10 years on Mac) and I am pretty happy the way it is now. but happy to roll up my sleeves, cry a lot and fight this beast if it is for better.

**Comment by elbys** [comment]
@JeanLoureiro  

> if I understood you question well. We can use Material UI library as Simple Components (Buttons, Typography, Cards, Grid and > so on) and put them together on the fly when we need them rather than building a component grouping them.

I am not sure I agree with that.... As I understood, we agreed that there needs to be room for complex composition as long as the component holds the opinion of DHI design.  If we don't think this is the right repo for this then we will have to do another repo.  Maybe having repo with both types of components can be too much and we should split that. If not we could split the repo between full punch and complex composition components. 

>The existing setup looks sufficient, though it would be nice to eventually have a CI pipeline automate testing, linting, >versioning and publishing of the libraries - I think we would benefit from very fast and frequent automated releases.

I also like this idea... We could use github boards to start putting task to complete then we can find the people to help

**Comment by rosudhi** [comment]
just my opinion:
- every component should have it's storybook, this way, we could see easily how the component(s) will look like.
- linting is mandatory, we should keep our codes good, clean, and well formatted.
- testing is mandatory, which makes our component robust and stable.
and everything are lovely to have in automation way (CI).

> The existing setup looks sufficient, though it would be nice to eventually have a CI pipeline automate testing, linting, versioning and publishing of the libraries - I think we would benefit from very fast and frequent automated releases.
like this

**Comment by goneale** [comment]
Hi guys

Sharing a few thoughts on the above.

Re. @JeanLoureiro & @elbys, I understand the wish for complex composition comprising of a few smaller components to bring benefit via reusability and not reintroducing the same thing over and over in your own projects. However.. The theme or mission with react-components I believe, representing point of view from our team here at Seaport OPX,

### **Is it valuable, is it generic, is it useful to a wide audience?**

If we can answer **YES** to this question, there is a good chance it should exist in. If there is a component used heavily in one department and it's wished to bring into react-components, but it is too opinionated/business case-specific and probably won't give valuable to the others more widely, it probably should stay in it's parent project, or in it's own component library you reference in your own department.

## In or Out?
Let's take some examples.. I'd like to make reference to a few components without rustling too many feathers here perhaps ;)

For example, I look at this component. `Modal`. Great, I see it appears to be customised somewhat from Material UI, some nice shadows, background colours to delineate content sections etc. A universal modal standardising a style we could all use, you could say.
https://bit.dev/dhi-solutions/shared/ui/modal

However I would struggle accepting this into `react-components`. I would ask these questions,

1) Does this component give a good deal of tangible benefit to consumers above the standard Material UI modal? Maybe.. what extra logic is happening inside <Modal> that we don't want to write every time? What if each department in DHI wanted a slightly different design, or were forced to due to client expectations?
2) I may not want the box shadow, or more specifically the responsive full screen style, but rather a max-width: 600 etc.

Components which have a high level of opinionated user design/experience, and are only a thin layer on top become harder to justify and start eroding at it's justification in a shared library.

Now to play devil's advocate here, I *love* the idea we could standard the design and layout amongst DHI projects, because as we all know as developers (once we have something awesome, why change it? Everyone should use this one :) ) so the Modal design itself, is awesome. So the ability to come together and all gravitate towards a consistent layout and theme amongst the business as a whole, is only better for consistency between each department and in turn best for DHI as a whole.

So if we decide that (forgive me I don't know much about mike-shared components, and I believe they might be trying to achieve similar) then maybe these sort of components get the tick ✅.

But now moving on in contrast to a component I feel holds a lot of strength on it's own, is very little opinionated from the industry standard and I believe many departments would take advantage of (as we've also had to do something similar) is this control,
https://bit.dev/dhi-solutions/shared/ui/legend

Most of the time you can agree, a unit legend like this is going to run horizontal or vertical (controlled with a prop) be block based on gradient-based and divided into buckets. We don't want to design this with divs each time and have every department do it a different way. Why reinvent the wheel, a perfect fit for react-components.

## Requirements Checklist
Finally, I think we perhaps as a team put together a 5 step checklist, just like with some open source repositories when opening an issue you have to ensure your issue fits the checklist before raising the issue, we ensure a proposed component fits the requirements checklist for it to be a good fit for react-components. Any bullet points on this, let's start jotting them down...

## Unit tests/linting/code styling/storybook
We probably should explore this, how mature and beneficial is React UI-based unit testing? We typically deal with business logic unit tests here at SPOPX but are also exploring React unit tests. Linting, storybook, code-styling requirements fantastic suggestions and mandatory agreed with @rosudhi and @rihr 

Regards,
Graham
SPOPX

**Comment by j08lue** [comment]
Thanks for picking up on this, @goneale.

We discussed this thread in a dev meeting attended by DK and IN frontenders (@rihr @bertearazvan @elbys @jharper93 @rosudhi @MadsZeneli and more).

As you know, we would like to find out very soon where we can share what kinds of components across the company, because we - unlike you, here - do not have established a go-to solution and every week without one means more stuff that is left unshared. If we can agree on a wide enough scope for this repo to accommodate many of the components we would like to share, that would be a nice step towards an integrated DHI platform.

Our main motivation for sharing is to achieve a common look and feel of frontends developed across DHI. The definition of that look and feel is, in our view, in very good hands with the DHI UI/UX design team, which publishes the very detailed [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines). Any component that carefully implements these guidelines (unless it is so simple it can be just a MUI component styled through the theme), is for us valuable for sharing even when trivial in function, because getting all the details of the design right is not easy, as you surely know. In short, opinionated is good, if the opinion comes from the DHI design guidelines (or careful extrapolation from them).

So to get the checklist started, how about these criteria that might set the lower bound on value for you:

- [x] The component cannot be implemented by styling a MUI component via the theme
- [x] The component implements an element of the [DHI Design Guidelines](https://www.figma.com/file/pSfX5GNsa6xhKGbi3DWQtn/DHI-Official-Guidelines) or is otherwise generic enough in functionality and close enough to the DHI CVI that it is likely to find reuse in other projects

We furthermore propose to set up a [lab package like MUI has](https://material-ui.com/components/about-the-lab/) where components can go until they have proven to get used and have passed style and quality checks. This would allow us to start working on this fast, gather some experience on what kinds of components get shared and what their value is, and then refine the criteria for them to make it into a core package.

So my questions to move forward would be
1. Do you support opening the scope of the repo towards the opinionated, at times stupid, components we want to share?
1. What other points would you like to have on the checklist?
1. How about a lab?

**Comment by goneale** [comment]
Hi Jonas,

Sorry for the late reply. It has been very busy here as we get closer to sprint wrap-up time of the fortnight.

I believe we are all on the same page here, I like the checklist proposed and I like the idea of a "lab package" to trial components that may need more discussion before entering the mature component area. I'm sorry I'm a bit time-poor to add more to the checklist right now.

So you aren't blocked, proceed with introducing your necessary components and functionality into react-components on a branch so you can move along, raise a PR for works and as discussed, I believe we decided on.. the "head" for each department will be responsible for discussing the proposed changes to be introduced with their local team and ultimately reviewing and stamping their approval on the PR.

When each head of dept has stamped their approval we can perform a merge, does that sound good?

This is our library jointly, not SPOPX's, not DHI's and we all should have a say on how things run.

Thanks for all your ideas
Speak with you soon
